### ISSUE TITLE
Explain how to use openshift connection more clearly

### ISSUE THREAD

**Issue by djgalloway** [ceph/ceph-medic#113]
The docs mention the new `openshift` and `kubernetes` connections but not how they communicate with the cluster(s).

I have an OpenShift 4 cluster up and want to communicate with it just using the standard `oc` command if possible.  Currently, it looks like ceph-medic tries to use the minishift method of communicating with a specific cluster by using contexts.

If the context isn't defined, I think ceph-medic should fall back to just trying to run `oc`.

**Comment by alfredodeza** [comment]
Fixing this ticket will mean updating the docs to mention that kubernetes uses `kubectl` and openshift uses `oc`. These commands are shown in the file log, for example:

```
 oc --context 3 exec -i -n rook-ceph rook-ceph-mon-b-958cf7785-2cstl -- /bin/sh -c python
 oc --context 3 --request-timeout=5 get -n rook-ceph pods -o json
```
