### ISSUE TITLE
check: warn on unreasonable OSD configured ratios

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-medic#134]
Todo: get clarity on what is an unreasonable value for an OSD configured ratio (from `ceph osd dump`)

**Comment by jeanchlopez** [comment]
The default ration are osd_full_ratio = 0.95 and osd_nearfull_ratio = 0.85

Would be best to get a warning if one of them has been modified

Would be best to get an error if the full ratio is above 0.95 has it reduces the margin of operation before the OSD is completely full.

**Comment by jeanchlopez** [comment]
ceph osd dump -f json-pretty | jq '. | {backfillfull_ratio, nearfull_ratio, full_ratio}'

Gives you all you need

**Comment by alfredodeza** [comment]
Excellent!
