### ISSUE TITLE
nit: wrong hosts number

### ISSUE THREAD

**Issue by Liuchang0812** [ceph/ceph-medic#44]
ceph-medic says that:

```
201 passed, on 2 hosts
```

actually, I have almost 40 hosts.

**Comment by alfredodeza** [comment]
Can you paste the complete section of the header? where it shows all the nodes and types? I think I know what is going on here, but want to double check. Thanks for reporting!

**Comment by alfredodeza** [comment]
Yeah, I know what is going on here:

    
    =======================  Starting remote check session  ========================
    Version: 1.0.0    Cluster Name: "ceph"
    Total hosts: [2]
    OSDs:    2    MONs:    0     Clients:    0
    MDSs:    0    RGWs:    0     MGRs:       0
    
    ================================================================================
    
    ------------ osds ------------
     node3
       ECOM1: /etc/ceph/ceph.conf does not exist
     node2
       ECOM1: /etc/ceph/ceph.conf does not exist
    
    8 passed, 2 failed, 2 errors, on 1 hosts

The runner is counting daemon types, not hosts.

/cc @andrewschoen

**Comment by Liuchang0812** [comment]
@alfredodeza yeah, you are right. I give ceph-medic only OSDs&MONs.  so, it is by design?

**Comment by alfredodeza** [comment]
@Liuchang0812 it is a bug! :( 

Fixing it now though!

**Comment by alfredodeza** [comment]
@Liuchang0812 can you try that branch (total-hosts) or the actual commit: https://github.com/ceph/ceph-medic/pull/45/commits/e1682cf61990f7183858ee15c3ec453a1846e9ee and let us know how that works for you?

**Comment by Liuchang0812** [comment]
@alfredodeza I tested in my cluster. It works! additional, `ceph-medic` is a great tool. 

```
=======================  Starting remote check session  ========================
Version: 1.0.0    Cluster Name: "ceph"
Total hosts: [39]
OSDs:   36    MONs:    3     Clients:    0
MDSs:    0    RGWs:    0     MGRs:       0

================================================================================

------------ osds ------------
 node11
 node10
 node13
 node12
 node15
 node14
 node17
 node16
 node19
 node18
 node31
 node30
 node37
 node36
 node35
 node34
 node33
 node32
 node28
 node29
 node24
 node25
 node26
 node27
 node20
 node22
 node23
 node9
 node8
 node1
 node3
 node2
 node5
 node4
 node7
 node6

------------ mons ------------
 node39
 node38
 node40

201 passed, on 39 hosts
```

**Comment by andrewschoen** [comment]
closed by https://github.com/ceph/ceph-medic/pull/45
