### ISSUE TITLE
checks: osd `nearfull: True`

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-medic#5]
If the `ceph osd df`, or `ceph -s -f json-pretty` is saying that the cluster is `nearfull` this sould be a warning

- [x] create a collector for `ceph -s --format=json` that gets loaded as a dict and added to the 'ceph' portion of the collector
- [x] write a check that validates that the cluster is not `nearfull`

**Comment by gabriellasroman** [comment]
Resolved with PR #139
