### ISSUE TITLE
checks: rgw_num_rados_handles should be 1

### ISSUE THREAD

**Issue by haklein** [ceph/ceph-medic#79]
It'd be nice to have a check for rgw_num_rados_handles. It shouldn't be set to values higher than 1. It will cause a lot of memory growth in RadosGW at little benefit. Also possible races in multisite.

**Comment by mattbenjamin** [comment]
+1

**Comment by alfredodeza** [comment]
@haklein do you know what the command would be to check for this?

**Comment by theanalyst** [comment]
Isn't 1 too less a value, for clusters with decent sizes shouldn't 2-4 be ok?

**Comment by haklein** [comment]
depends a bit on sync/async, num of OSDs, etc. But with virtualised or containerised RGWs scalability would preferably achieved via multiple RGWs anyway.. @oritwas mentioned possible multisite issues with >1 and huge number of objects.
@alfredodeza: something like that should do per RGW instance:
# ceph daemon client.rgw.rdh-cu-8 config show | grep rgw_num_rados_handles
    "rgw_num_rados_handles": "1",

But preferably this would be checked via json parsing.
Depending on the discussion with @theanalyst we might consider just printing a warning.

**Comment by alfredodeza** [comment]
I ended up using `ceph --admin-deamon /path/to/socket  config show`, which works great
