### ISSUE TITLE
ceph-medic project does not exist (anymore) in tracker.ceph.com

### ISSUE THREAD

**Issue by hydro-b** [ceph/ceph-medic#87]
Before any contributions, a reference ticket must exist. The community issue tracker is hosted at tracker.ceph.com

To open a new issue, requests can go to:

http://tracker.ceph.com/projects/ceph-medic/issues/new

^^ So either the CONTRIBUTING.rst should be changed or the ceph-medic project in tracker.ceph.com should be created.

**Comment by dmick** [comment]
What does ceph-redmine have to do with ceph-medic (and for that matter what
is ceph-redmine exactly)?

**Comment by hydro-b** [comment]
Hmm, what I meant to say was that "https://tracker.ceph.com/projects/ceph-medic/issues/new" gives a 404. So that indicates that the "ceph-medic" "project" does not exist (anymore) in tracker.ceph.com (redmine). And, because the "CONTRIBUTING.rst" states that before opening an issue you need a redmine ticket number. But as that's not possible I created this issue. Does this make it more clear?

**Comment by dmick** [comment]
Right.  ceph-medic is missing as a project from tracker.ceph.com.  I shall inquire as to why this is.

**Comment by alfredodeza** [comment]
This is a valid issue, the docs are incorrect, and there is no need for issues to be on redmine, here on Github is fine.

**Comment by alfredodeza** [comment]
Fixed with 2ca3e3b9ac905a6a1ef968692f56bf05f06d366e
